### ISSUE TITLE
Connect bouncer to a non local lapi

### ISSUE THREAD

**Issue by GJurriens** [thespad/docker-traefik-crowdsec-bouncer#10]
Hello,

Maybe it's just me not getting it, but I'm trying to make the traefik-crowdsec-bouncer work with a lapi server on another host. I did manage to get the agent to communicate to the lapi server (https://lapi-server.domain.com/), but I have no idea what environment variable or whatever I need to add to make the bouncer look at the main lapi server for decisions.

Can anyone help me out here with an example?

**Comment by thespad** [comment]
`CROWDSEC_AGENT_HOST` controls the LAPI endpoint the bouncer uses to query decisions.

**Comment by GJurriens** [comment]
Oke, but should I enter https://lapi-server.domain.com or lapi-server.domain.com:443?
I seem to have tried both, but I didn't get to see any additional bouncers in my list (using cscli bouncers list), It does state the name as I had to pre-register it to get the api key, but IP Addres, Type and version stay empty...

**Comment by thespad** [comment]
Use `CROWDSEC_BOUNCER_SCHEME` to set http/https and then you only need to provide a port if it differs from 80/443 respectively.

**Comment by GJurriens** [comment]
Thank you for your time and fast responses, but unfortunately I cannot seem to get it to work. I know the port is open on the lapi server as the agent is correctly connected over https.
Maybe you can find something in my config that is wrong, I have no idea at the moment why it does not work (I bet it is my fault somewhere, but I don't see it yet)
```
bouncer-traefik:
    image: docker.io/fbonalair/traefik-crowdsec-bouncer:latest
    container_name: bouncer-traefik
    environment:
      CROWDSEC_BOUNCER_API_KEY: generated-api-key
      CROWDSEC_AGENT_HOST: lapi-server.domain.com
      CROWDSEC_BOUNCER_SCHEME: https
#      PORT: 443
#      CROWDSEC_BOUNCER_LOG_LEVEL: 1
      GIN_MODE: release
    networks:
      - proxy # same network as traefik + crowdsec
    restart: unless-stopped
```
